# Generated by Django 4.0 on 2021-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDataBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='data/building/bulkupload/')),
            ],
            options={
                'db_table': 'building_data_bulk_upload',
            },
        ),
        migrations.CreateModel(
            name='HalfHourlyDataBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='data/halfhourly/bulkupload/')),
            ],
            options={
                'db_table': 'half_hour_data_bulk_upload',
            },
        ),
        migrations.CreateModel(
            name='MeterDataBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='data/meter/bulkupload/')),
            ],
            options={
                'db_table': 'meter_data_bulk_upload',
            },
        ),
    ]
