# Generated by Django 4.0 on 2021-12-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_consumption', '0002_buildingdatabulkupload_halfhourlydatabulkupload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingdatabulkupload',
            old_name='csv_file',
            new_name='building_csv_file',
        ),
        migrations.RenameField(
            model_name='halfhourlydatabulkupload',
            old_name='csv_file',
            new_name='half_hour_csv_file',
        ),
        migrations.RenameField(
            model_name='meterdatabulkupload',
            old_name='csv_file',
            new_name='meter_csv_file',
        ),
    ]
