# Generated by Django 4.0 on 2021-12-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_consumption', '0004_alter_buildingdata_id_alter_halfhourlydata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfhourlydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
